Models/Category.cs
namespace FinalProject.Models
{
    public class Category
    {
        public Guid IdKategori { get; set; }

        public string NamaKategori { get; set; } = null!;

        public virtual ICollection<Product> TabelBarangs { get; set; } = new List<Product>();
    }
}

Models/ErrorViewModel.cs
namespace FinalProject.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Product.cs
namespace FinalProject.Models
{
    public class Product
    {
        public Guid IdBarang { get; set; }

        public string NamaBarang { get; set; } = null!;

        public int Stock { get; set; }

        public int Harga { get; set; }

        public Guid IdKategori { get; set; }

        public string? Deskripsi { get; set; }

        public virtual Category? IdKategoriNavigation { get; set; }
    }
}

Controllers/AdminController/CategoriesController.cs
using FinalProject.Models;
using FinalProject.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;

namespace FinalProject.Controllers.AdminController;

public class CategoriesController : Controller
{
    private readonly CategoryInterface _category;

    public CategoriesController(CategoryInterface _category)
    {
        this._category = _category;
    }

    public async Task<IActionResult> Index()
    {
        ViewBag.Class = "Admin";
        ViewBag.CurrentTable = "Product Type";

        List<Category> categories = await _category.GetCategoriesAsync();

        return View(categories);
    }

    [HttpGet]
    public async Task<JsonResult> GetCategoryById(Guid id)
    {
        Category category = await _category.GetCategoryAsync(id);

        return Json(category);
    }

    public async Task<IActionResult> CreateCategory(Category category)
    {
        await _category.CreateCategory(category);

        return RedirectToAction("Index");
    }

    public async Task<IActionResult> UpdateCategory(Category category)
    {
        await _category.UpdateCategory(category);

        return RedirectToAction("Index");
    }



    public async Task<IActionResult> DeleteCategory(Guid id)
    {
        await _category.DeleteCategory(id);

        return RedirectToAction("Index");
    }
}

Controllers/AdminController/ProductsController.cs
using FinalProject.Models;
using FinalProject.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FinalProject.Controllers.AdminController
{
    public class ProductsController : Controller
    {
        private readonly ProductInterface _product;
        private readonly CategoryInterface _category;

        public ProductsController(ProductInterface _product, CategoryInterface _category)
        {
            this._product = _product; 
            this._category = _category;
        }

        public async Task<IActionResult> Index()
        {
            List<Product> products = await _product.GetProductsAsync();
            List<Category> categories = await _category.GetCategoriesAsync();
            List<SelectListItem> dropdownItems = new List<SelectListItem>();

            foreach (var item in categories)
            {
                dropdownItems.Add(new SelectListItem
                {
                    Text = item.NamaKategori,
                    Value = item.IdKategori.ToString()
                });
            }

            ViewBag.Class = "Admin";
            ViewBag.CurrentTable = "Product";
            ViewBag.CategoriesDropdown = dropdownItems;

            return View(products);
        }

        [HttpGet]
        public async Task<JsonResult> GetProductById(Guid id)
        {
            Product product = await _product.GetProductAsync(id);

            return Json(product);
        }

        public async Task<IActionResult> CreateProduct(Product product)
        {
            await _product.CreateProduct(product);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> UpdateProduct(Product product)
        {
            await _product.UpdateProduct(product);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteProduct(Guid id)
        {
            await _product.DeleteProduct(id);

            return RedirectToAction("Index");
        }
    }
}

Controllers/HomeController.cs
using FinalProject.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FinalProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/TransactionsController.cs
using FinalProject.Models;
using FinalProject.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace FinalProject.Controllers;

public class TransactionsController : Controller
{
    private readonly ProductInterface _product;
    private readonly TransactionInterface _transaction;

    public TransactionsController(ProductInterface _product, TransactionInterface _transaction)
    {
        this._product = _product;
        this._transaction = _transaction;
    }

    public async Task<IActionResult> Index()
    {
        List<Product> products = await _product.GetProductsAsync();

        ViewBag.Class = "Beli Barang";

        return View(products);
    }

    public async Task<IActionResult> CreateTransaction(int total, Product product)
    {
        var response = await _transaction.CreateTransaction(total, product);

        TempData["message"] = await response.Content.ReadAsStringAsync();
        TempData["statusCode"] = response.StatusCode;

        return RedirectToAction("Index");
    }
}

Views/Categories/index.cshtml
@model List<FinalProject.Models.Category>

@{
    Layout = "_Layout";
    ViewData["Title"] = "Product Type Page";
}
<head>

</head>
<body>
    <div class="text-center">
        <h1 class="display-4">Product Type</h1>
    </div>

    <div class="d-flex flex-row justify-content-center m-5">
        <a asp-controller="Categories" asp-action="Index" class="btn @(ViewBag.CurrentTable == "Product Type" ? "btn-danger" : "btn-light" )" style="width: 280px">Product Type</a>
        <a asp-controller="Products" asp-action="Index" class="btn @(ViewBag.CurrentTable == "Product" ? "btn-danger" : "btn-light" )" style="width: 280px">Product</a>
    </div>


    <div class="card mt-2">
        <div class="card-body student-list">
            <button type="button" data-bs-toggle="modal" data-bs-target="#CreateCategoryModal" class="btn btn-primary mb-2">Create New Product Type</button>
            <table class="table" id="ProductTypeTable">
                <thead>
                    <tr>
                        <th> Jenis Barang </th>
                        <th> Action </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td> @item.NamaKategori </td>
                            <td>
                                <button data-bs-toggle="modal" data-bs-target="#UpdateCategoryModal" id="@item.IdKategori" class="btn btn-warning">Update</button>
                                <a asp-controller="Categories" asp-route-id="@item.IdKategori" asp-action="DeleteCategory" onclick="return confirm('Are you sure you want to delete this item?');" class="btn btn-danger">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

    @* update modal *@
    <div class="modal fade" id="UpdateCategoryModal" tabindex="-1" aria-labelledby="UpdateCategoryModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="UpdateCategoryModalLabel">Update Category</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" asp-controller="Categories" asp-action="UpdateCategory">
                    <div class="modal-body">
                        <input type="hidden" id="IdKategori" name="IdKategori" />
                        <div class="mb-3">
                            <label class="form-label"> Nama Kategori </label>
                            <input type="text" id="NamaKategori" class="form-control" name="NamaKategori" />
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    @* create modal *@
    <div class="modal fade" id="CreateCategoryModal" tabindex="-1" aria-labelledby="CreateCategoryModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="CreateCategoryModalLabel">Create Category</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" asp-controller="Categories" asp-action="CreateCategory">
                    <div class="modal-body">
                        <div class="mb-3">
                            <label class="form-label"> Nama Kategori </label>
                            <input type="text" class="form-control" name="NamaKategori" />
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js" integrity="sha512-DUC8yqWf7ez3JD1jszxCWSVB0DMP78eOyBpMa5aJki1bIRARykviOuImIczkxlj1KhVSyS16w2FSQetkD4UU2w==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
@foreach (var item in Model)
{
    <script>
        $(function () {
            $('[id*=@item.IdKategori]').on('click', function () {
                $.get("Categories/GetCategoryById?id=" + "@item.IdKategori",
                    function (response) {
                        $('#IdKategori').val(response.idKategori);
                        $('#NamaKategori').val(response.namaKategori);
                    });
            });
        });
    </script>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Products/Index.cshtml
@model List<FinalProject.Models.Product>

@{
    Layout = "_Layout";
    ViewData["Title"] = "Product Page";
}
<head>

</head>
<body>
    <div class="text-center">
        <h1 class="display-4">Product</h1>
    </div>

    <div class="d-flex flex-row justify-content-center m-5">
        <a asp-controller="Categories" asp-action="Index" class="btn @(ViewBag.CurrentTable == "Product Type" ? "btn-danger" : "btn-light" )" style="width: 280px">Product Type</a>
        <a asp-controller="Products" asp-action="Index" class="btn @(ViewBag.CurrentTable == "Product" ? "btn-danger" : "btn-light" )" style="width: 280px">Product</a>
    </div>


    <div class="card mt-2">
        <div class="card-body student-list">
            <button type="button" data-bs-toggle="modal" data-bs-target="#CreateProductModal" class="btn btn-primary mb-2">Create New Product Type</button>
            <table class="table" id="ProductTypeTable">
                <thead>
                    <tr>
                        <th> Nama Barang </th>
                        <th> Jenis Barang </th>
                        <th> Deskripsi Barang </th>
                        <th> Jumlah Stock </th>
                        <th> Harga Satuan </th>
                        <th> Action </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td> @item.NamaBarang </td>
                            <td> @item.IdKategoriNavigation?.NamaKategori </td>
                            <td> @item.Deskripsi </td>
                            <td> @item.Stock </td>
                            <td>
                                @{ string newPriceFormat = String.Format("{0:N}", item.Harga); }

                                Rp @newPriceFormat
                            </td>
                            <td>
                                <button data-bs-toggle="modal" data-bs-target="#UpdateProductModal" id="@item.IdBarang" class="btn btn-warning">Update</button>
                                <a asp-controller="Products" asp-route-id="@item.IdBarang" asp-action="DeleteProduct" onclick="return confirm('Are you sure you want to delete this item?');" class="btn btn-danger">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

    @* update modal *@
    <div class="modal fade" id="UpdateProductModal" tabindex="-1" aria-labelledby="UpdateProductModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="UpdateProductModalLabel">Update Product</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" asp-controller="Products" asp-action="UpdateProduct">
                    <div class="modal-body">
                        <input type="hidden" id="IdBarang" name="IdBarang" />
                        <div class="mb-3">
                            <label class="form-label"> Nama Product </label>
                            <input type="text" id="NamaBarang" class="form-control" name="NamaBarang" />
                        </div>
                        <div class="mb-3">
                            <label class="form-label"> Jenis Barang </label>
                            @Html.DropDownList("IdKategori", (IEnumerable<SelectListItem>)ViewBag.CategoriesDropdown, new { @class = "form-control" })
                        </div>
                        <div class="mb-3">
                            <label class="form-label"> Deskripsi Barang</label>
                            <input type="text" class="form-control" id="Deskripsi" name="Deskripsi" />
                        </div>
                        <div class="mb-3">
                            <label class="form-label"> Stock </label>
                            <input type="number" id="Stock" class="form-control" name="Stock" />
                        </div>
                        <div class="mb-3">
                            <label class="form-label"> Harga Satuan </label>
                            <input type="number" id="Harga" class="form-control" name="Harga" />
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    @* create modal *@
    <div class="modal fade" id="CreateProductModal" tabindex="-1" aria-labelledby="CreateProductModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="CreateProductModalLabel">Create Product</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" asp-controller="Products" asp-action="CreateProduct">
                    <div class="modal-body">
                        <div class="mb-3">
                            <label class="form-label"> Nama Barang </label>
                            <input type="text" class="form-control" name="NamaBarang" />
                        </div>
                        <div class="mb-3">
                            <label class="form-label"> Jenis Barang </label>
                            @Html.DropDownList("IdKategori", (IEnumerable<SelectListItem>)ViewBag.CategoriesDropdown, new { @class = "form-control" })
                        </div>
                        <div class="mb-3">
                            <label class="form-label"> Deskripsi Barang</label>
                            <input type="text" class="form-control" id="Deskripsi" name="Deskripsi"/>
                        </div>
                        <div class="mb-3">
                            <label class="form-label"> Stock </label>
                            <input type="number" id="Stock" class="form-control" name="Stock" />
                        </div>
                        <div class="mb-3">
                            <label class="form-label"> Harga Satuan </label>
                            <input type="number" id="Harga" class="form-control" name="Harga" />
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js" integrity="sha512-DUC8yqWf7ez3JD1jszxCWSVB0DMP78eOyBpMa5aJki1bIRARykviOuImIczkxlj1KhVSyS16w2FSQetkD4UU2w==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
@foreach (var item in Model)
{
    <script>
        $(function () {
            $('[id*=@item.IdBarang]').on('click', function () {
                $.get("Products/GetProductById?id=" + "@item.IdBarang",
                    function (response) {
                        $('#IdBarang').val(response.idBarang);
                        $('#NamaBarang').val(response.namaBarang);
                        $('#IdKategori').val(response.idKategori);
                        $('#Deskripsi').val(response.deskripsi);
                        $('#Stock').val(response.stock);
                        $('#Harga').val(response.harga);
                    });
            });
        });
    </script>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FinalProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FinalProject.styles.css" asp-append-version="true" />
</head>
<body>
    <main class="d-flex flex-row" style="min-height: 1080px">
        <div class="d-flex flex-column flex-shrink-0 p-3 bg-light" style="width: 280px;">
            <ul class="nav nav-pills flex-column mb-auto pt-5">
                <li class="nav-item">
                    <a class="nav-link @(ViewBag.Class == "Admin" ? "link-danger" : "link-dark" )" asp-area="" asp-controller="Categories" asp-action="Index">
                        Admin
                    </a>
                </li>
                <li class="mt-5">
                    <a class="nav-link @(ViewBag.Class == "Beli Barang" ? "link-danger" : "link-dark" )" asp-area="" asp-controller="Transactions" asp-action="Index">
                        Beli Barang
                    </a>
                </li>
                <li class="mt-5">
                    <a href="#" class="nav-link link-dark">
                        Logout
                    </a>
                </li>
            </ul>
        </div>
        <div class="container">
            @RenderBody()
        </div>
    </main>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Transactions/Index.cshtml
@model List<FinalProject.Models.Product>

@{
    Layout = "_Layout";
    ViewData["Title"] = "Transaction Page";
}
<head>

</head>
<body>
    <div class="text-center">
        <h1 class="display-4">Transaksi</h1>
    </div>

    <div class="card mt-2">
        <div class="card-body student-list">
            <table class="table">
                <thead>
                    <tr>
                        <th> Nama Barang </th>
                        <th> Jenis Barang </th>
                        <th> Deskripsi Barang </th>
                        <th> Jumlah Stock </th>
                        <th> Harga Satuan </th>
                        <th> Action </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td> @item.NamaBarang </td>
                            <td> @item.IdKategoriNavigation?.NamaKategori </td>
                            <td> @item.Deskripsi </td>
                            <td> @item.Stock </td>
                            <td>
                                @{
                                    string newPriceFormat = String.Format("{0:N}", item.Harga);
                                }

                                Rp @newPriceFormat
                            </td>
                            <td>
                                <button data-bs-toggle="modal" data-bs-target="#TransactionModal" id="@item.IdBarang" class="btn btn-warning">Beli</button>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

    @* modal after transaction *@
    <div class="modal fade" id="MessageModal" tabindex="-1" aria-labelledby="MessageLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <h1 class="modal-title text-center" id="Messa">@TempData["message"]</h1>
                </div>

            </div>
        </div>
    </div>

    @* transaction modal *@
    <div class="modal fade" id="TransactionModal" tabindex="-1" aria-labelledby="TransactionModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="TransactionModalLabel">Beli</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" asp-controller="Transactions" asp-action="CreateTransaction">
                    <div class="modal-body">
                        <input type="hidden" name="IdBarang" id="IdBarang" />
                        <div class="mb-3">
                            <label class="form-label"> Nama Barang </label>
                            <input type="text" class="form-control" id="NamaBarang" name="NamaBarang" disabled/>
                        </div>
                        <div class="mb-3">
                            <label class="form-label"> Stock </label>
                            <input type="number" id="Stock" class="form-control" name="Stock" disabled/>
                        </div>
                        <div class="mb-3">
                            <label class="form-label"> Harga Satuan </label>
                            <input type="number" id="Harga" class="form-control" name="Harga" disabled/>
                        </div>
                        <div class="mb-3">
                            <label class="form-label"> Jumlah Beli </label>
                            <input type="number" id="Total" class="form-control" name="Total" />
                        </div>
                        <div>
                            <div class="mb-3">
                                <h3>Total</h3>
                                <p type="number" id="TotalBayar"> </p>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary disabled" id="submitButton">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js" integrity="sha512-DUC8yqWf7ez3JD1jszxCWSVB0DMP78eOyBpMa5aJki1bIRARykviOuImIczkxlj1KhVSyS16w2FSQetkD4UU2w==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
@foreach (var item in Model)
{
    string numberFormat = String.Format("{0:N}", item.Harga);
    <script>
        $(function () {
            $('[id*=@item.IdBarang]').on('click', function () {
                $.get("Products/GetProductById?id=" + "@item.IdBarang",
                    function (response) {
                        $('#IdBarang').val(response.idBarang);
                        $('#NamaBarang').val(response.namaBarang);
                        $('#Stock').val(response.stock);
                        $('#Harga').val(response.harga);
                        $('#TotalBayar').html("Rp @numberFormat");
                    });
            });
        });
    </script>
}

<script>
    let numberFormat = new Intl.NumberFormat('id-ID', {
        style: 'currency',
        currency: 'IDR',
    });

    $('#Total').on('keyup', function () {
        let total = parseInt($('#Total').val());
        let price = parseInt($('#Harga').val());

        if (total > 0) {
            $('#TotalBayar').html(numberFormat.format(total * price));
            $('#submitButton').removeClass('disabled');
        } else {
            $('#TotalBayar').html(0);
            $('#submitButton').addClass('disabled');
        }
    });
</script>

@if (TempData["statusCode"] != null)
{
    <script>
        $(window).on('load', function () {
            $('#MessageModal').modal('show');
        });
    </script>
}